### ISSUE TITLE
flex和flex-grow在实际使用中的区别

### ISSUE THREAD

**Issue by DrakeYL** [longyuanJason/blog#1]
flex是flex-grow、flex-shrink和flex-basis这三个属性的简写属性，**实际使用中强烈建议使用flex而不是分开写这三个属性**。

使用flex属性时，如果不显示设置flex-shrink和flex-basis属性，flex-shrink属性默认值为1，flex-basis默认值为0%。

比如`.item{flex: 1}`等同于`.item{flex-grow:1;flex-shrink:1;flex-basis:0%;}`。考虑下面的代码，由于flex-basis为0%，所以元素设置的width值没有生效，各元素按flex-grow的权重值得到宽度：总权重为1+2+2=5，所以三个元素的宽度分别为500 * 1 / 5=100px,500 * 2  / 5=200px,500 * 2 / 5=200px。

如果单独使用flex-grow`.item{flex-grow: 1}`，那么由于flex-basis的默认值是auto，为元素设置的width会生效，那么还剩下500-50-100-150=200px的剩余空间，这200px会根据flex-grow的值进行分配，总权重是5，每一份是40,所以最后三个子元素的宽度分别是50+40=90px，100+80=180px,150+80=230px。

```css
        .container {
            display: flex;
            width: 500px;
            background-color: grey;
            height: 100px;
        }

        .children1 {
            width: 50px;
            flex: 1;
            background-color: yellow;
        }

        .children2 {
            width: 100px;
            flex: 2;
            background-color: green;
        }

        .children3 {
            width: 150px;
            flex: 2;
            background-color: blue;
        }
```
```html
    <div class="container">
        <a class="children1"></a>
        <a class="children2"></a>
        <a class="children3"></a>
    </div>
```
```{flex: 1;}```
![flex-1](https://user-images.githubusercontent.com/30164363/92926602-d9731800-f46e-11ea-8462-1b1c42b4480b.png)

```{flex-grow: 1;}```
![image](https://user-images.githubusercontent.com/30164363/92927155-bf860500-f46f-11ea-8608-9d23043fcacd.png)
